//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.13.1
//     from Assets/Scripts/KeyBoardInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/KeyBoardInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @KeyBoardInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @KeyBoardInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""KeyBoardInputActions"",
    ""maps"": [
        {
            ""name"": ""Car"",
            ""id"": ""a0036ea9-bffd-4917-b8f7-9d7153a2f161"",
            ""actions"": [
                {
                    ""name"": ""FrontMoveKeyBoard"",
                    ""type"": ""Value"",
                    ""id"": ""ba5ec858-3c59-4c96-a1dc-a27e8dcaf81f"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FrontMoveSteeringWheel"",
                    ""type"": ""Value"",
                    ""id"": ""b001e9d9-39e1-4003-8e0c-94e0903c54e5"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftRightMoveKeyBoard"",
                    ""type"": ""Value"",
                    ""id"": ""6596cca0-98e3-4691-b988-f34517693459"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftRightMoveSteeringWheel"",
                    ""type"": ""Value"",
                    ""id"": ""6a8cf518-f2c4-4bad-9584-480ee83382c1"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BreakKeyBoard"",
                    ""type"": ""Value"",
                    ""id"": ""68e05661-ec53-4fa2-96c3-a6425ee83ce3"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BreakSteeringWheel"",
                    ""type"": ""Value"",
                    ""id"": ""74ee1dbe-2685-4171-9e8a-c9337236b4b0"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftRightKeyBoard"",
                    ""type"": ""Value"",
                    ""id"": ""3f9c8469-e7ab-4707-aec3-da4a014a832a"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftRightSteeringWheel"",
                    ""type"": ""Value"",
                    ""id"": ""ca3d2406-992c-4418-9670-a06c8ea9b9ee"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UpDownKeyBoard"",
                    ""type"": ""Value"",
                    ""id"": ""41958b4a-2cc8-4a28-92f6-44be3a756340"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UpDownSteeringWheel"",
                    ""type"": ""Value"",
                    ""id"": ""e5c9c5ca-c590-42ff-b359-a9dda62611d8"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LightControlKeyBoard"",
                    ""type"": ""Button"",
                    ""id"": ""fc162b0a-92cd-4e8e-817a-3f7474711eaf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LightControlSteeringWheel"",
                    ""type"": ""Button"",
                    ""id"": ""eaaa6aa4-87f0-4863-b023-932034cb9add"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GearChangeKeyBoard"",
                    ""type"": ""Button"",
                    ""id"": ""82686259-71cb-4b03-9108-dc23d1046ed1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GearChangeSteeringWheel"",
                    ""type"": ""Button"",
                    ""id"": ""118b53b4-0758-4a4a-97de-e05e7a122869"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SideBreakKeyBoard"",
                    ""type"": ""Button"",
                    ""id"": ""9d9bcee7-957b-4e23-a592-607c98969a5c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SideBreakSteeringWheel"",
                    ""type"": ""Button"",
                    ""id"": ""bfcb4312-fff0-4fa0-a574-6adbc8d7539f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SettingsKeyBoard"",
                    ""type"": ""Button"",
                    ""id"": ""5ed7fe1d-b9f2-4bc7-a1c2-b52e2d1a6cda"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SettingsSteeringWheel"",
                    ""type"": ""Button"",
                    ""id"": ""ae42fe20-259c-421c-982c-dc09946bd04a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectKeyBoard"",
                    ""type"": ""Button"",
                    ""id"": ""84ef3a1b-711d-48ad-949c-e53851520d29"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectSteeringWheel"",
                    ""type"": ""Button"",
                    ""id"": ""5f643888-5de6-410b-bfca-37d24826ba14"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UndoKeyBoard"",
                    ""type"": ""Button"",
                    ""id"": ""f357fd35-ceaa-46a7-b9fd-1df6ddbcea9b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UndoSteeringWheel"",
                    ""type"": ""Button"",
                    ""id"": ""df93c5c4-4a0d-4842-bc14-50172e782e33"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2d3ec518-8fa7-4675-ac87-bfd2daaeebb9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""FrontMoveKeyBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1928dbe2-0703-4ad4-a6f9-9e3c63de521a"",
                    ""path"": ""<HID::Wired Wheel>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Steering Wheel"",
                    ""action"": ""FrontMoveSteeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""9c750f1d-4179-44b3-a839-545b3db79fbe"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftRightMoveKeyBoard"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""864548d4-d0dd-475c-b6c1-60d9595d40ee"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""LeftRightMoveKeyBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""717c1412-03eb-4e48-ac33-e63b0147aaed"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""LeftRightMoveKeyBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""ba3a79fb-1475-4c41-af40-b8332f71fa0a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftRightMoveSteeringWheel"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""20b9d143-a71b-4c64-80c8-030e96510f15"",
                    ""path"": ""<HID::Wired Wheel>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Steering Wheel"",
                    ""action"": ""LeftRightMoveSteeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f78d16e1-ec10-4218-a4ed-9e3e97e7cac9"",
                    ""path"": ""<HID::Wired Wheel>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Steering Wheel"",
                    ""action"": ""LeftRightMoveSteeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d366074a-4c09-4ac7-909d-91091275cce8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""BreakKeyBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a20c8db2-59ce-4199-8592-11353781a9df"",
                    ""path"": ""<HID::Wired Wheel>/rz"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Steering Wheel"",
                    ""action"": ""BreakSteeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""fd69f051-a9b0-4c81-bc4b-3b2cef4b16e7"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftRightKeyBoard"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0befa851-a18d-4a3a-88a7-a97ebb649e0c"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""LeftRightKeyBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ccac7307-5d22-4f0b-aa51-edc661c53125"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""LeftRightKeyBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""b49c5ede-1767-46c2-a58d-6c09b97bf7fb"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftRightSteeringWheel"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""012d81fc-2b46-4d25-be57-ab55e859611b"",
                    ""path"": ""<HID::Wired Wheel>/hat/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Steering Wheel"",
                    ""action"": ""LeftRightSteeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0644e6b2-41c2-452c-9416-80de08273a0e"",
                    ""path"": ""<HID::Wired Wheel>/hat/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Steering Wheel"",
                    ""action"": ""LeftRightSteeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""b3c94f76-30c6-4f48-bb0b-cf25121a0bb6"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpDownKeyBoard"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c3cbf044-3c2b-4f2a-803d-8922fcb5a365"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""UpDownKeyBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f1b81cda-3989-4245-8391-ab9096201acf"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""UpDownKeyBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""1e0b1e0c-1e7b-483e-8eaf-c94366a105b1"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpDownSteeringWheel"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""b29e54d3-017c-4523-adb9-7c318e4295a9"",
                    ""path"": ""<HID::Wired Wheel>/hat/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Steering Wheel"",
                    ""action"": ""UpDownSteeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2051ad8f-146f-44e5-9b45-dcd7811a3afb"",
                    ""path"": ""<HID::Wired Wheel>/hat/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Steering Wheel"",
                    ""action"": ""UpDownSteeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""87856a91-8cce-4a59-b483-d1df1d20ef25"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""LightControlKeyBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1bb5b74e-46a2-46b7-a02a-2f0c703ea475"",
                    ""path"": ""<HID::Wired Wheel>/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Steering Wheel"",
                    ""action"": ""LightControlSteeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f568014-d9ab-4a01-95bc-25ff985b1412"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""GearChangeKeyBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e0655a4-992e-4cd5-8887-23eb228254f1"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""GearChangeKeyBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93b0f1b6-430a-4d15-9f6f-5986f7369ac9"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""GearChangeKeyBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""840de1d8-20f7-4776-8ebe-be9f318dc5a1"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""GearChangeKeyBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""282c01be-388f-4543-8d95-70acbaeedd2e"",
                    ""path"": ""<HID::Wired Wheel>/button17"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Steering Wheel"",
                    ""action"": ""GearChangeSteeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""717ae1c5-2c97-4ca6-8de5-18e506aa64e9"",
                    ""path"": ""<HID::Wired Wheel>/button18"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Steering Wheel"",
                    ""action"": ""GearChangeSteeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3678b50-8530-4137-949c-2400afc65872"",
                    ""path"": ""<HID::Wired Wheel>/button21"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Steering Wheel"",
                    ""action"": ""GearChangeSteeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1923bf15-1a75-472f-93d6-ac563a6241fa"",
                    ""path"": ""<HID::Wired Wheel>/button22"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Steering Wheel"",
                    ""action"": ""GearChangeSteeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3bc8b662-33b5-49e0-8f41-a377d23969ca"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""SideBreakKeyBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8076882e-c532-4812-93b0-8f606ce3af20"",
                    ""path"": ""<HID::Wired Wheel>/button16"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Steering Wheel"",
                    ""action"": ""SideBreakSteeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a9f1dd1-4647-4514-888d-6ee769b69790"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""SettingsKeyBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51b3b88a-a70b-4cd4-a131-063b2bc3a2c5"",
                    ""path"": ""<HID::Wired Wheel>/button10"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Steering Wheel"",
                    ""action"": ""SettingsSteeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45ee13e4-f575-4f3d-8e4a-1f16c4a395a7"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""SelectKeyBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bed6c7b-cd67-4424-b84f-bf645985b357"",
                    ""path"": ""<HID::Wired Wheel>/button3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Steering Wheel"",
                    ""action"": ""SelectSteeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43b65f45-998d-47aa-bc92-9c6378562688"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard & Mouse"",
                    ""action"": ""UndoKeyBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20a53ece-97a7-40a7-bd80-25baa7198a1e"",
                    ""path"": ""<HID::Wired Wheel>/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Steering Wheel"",
                    ""action"": ""UndoSteeringWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard & Mouse"",
            ""bindingGroup"": ""Keyboard & Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Steering Wheel"",
            ""bindingGroup"": ""Steering Wheel"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<HID::Wired Wheel>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Car
        m_Car = asset.FindActionMap("Car", throwIfNotFound: true);
        m_Car_FrontMoveKeyBoard = m_Car.FindAction("FrontMoveKeyBoard", throwIfNotFound: true);
        m_Car_FrontMoveSteeringWheel = m_Car.FindAction("FrontMoveSteeringWheel", throwIfNotFound: true);
        m_Car_LeftRightMoveKeyBoard = m_Car.FindAction("LeftRightMoveKeyBoard", throwIfNotFound: true);
        m_Car_LeftRightMoveSteeringWheel = m_Car.FindAction("LeftRightMoveSteeringWheel", throwIfNotFound: true);
        m_Car_BreakKeyBoard = m_Car.FindAction("BreakKeyBoard", throwIfNotFound: true);
        m_Car_BreakSteeringWheel = m_Car.FindAction("BreakSteeringWheel", throwIfNotFound: true);
        m_Car_LeftRightKeyBoard = m_Car.FindAction("LeftRightKeyBoard", throwIfNotFound: true);
        m_Car_LeftRightSteeringWheel = m_Car.FindAction("LeftRightSteeringWheel", throwIfNotFound: true);
        m_Car_UpDownKeyBoard = m_Car.FindAction("UpDownKeyBoard", throwIfNotFound: true);
        m_Car_UpDownSteeringWheel = m_Car.FindAction("UpDownSteeringWheel", throwIfNotFound: true);
        m_Car_LightControlKeyBoard = m_Car.FindAction("LightControlKeyBoard", throwIfNotFound: true);
        m_Car_LightControlSteeringWheel = m_Car.FindAction("LightControlSteeringWheel", throwIfNotFound: true);
        m_Car_GearChangeKeyBoard = m_Car.FindAction("GearChangeKeyBoard", throwIfNotFound: true);
        m_Car_GearChangeSteeringWheel = m_Car.FindAction("GearChangeSteeringWheel", throwIfNotFound: true);
        m_Car_SideBreakKeyBoard = m_Car.FindAction("SideBreakKeyBoard", throwIfNotFound: true);
        m_Car_SideBreakSteeringWheel = m_Car.FindAction("SideBreakSteeringWheel", throwIfNotFound: true);
        m_Car_SettingsKeyBoard = m_Car.FindAction("SettingsKeyBoard", throwIfNotFound: true);
        m_Car_SettingsSteeringWheel = m_Car.FindAction("SettingsSteeringWheel", throwIfNotFound: true);
        m_Car_SelectKeyBoard = m_Car.FindAction("SelectKeyBoard", throwIfNotFound: true);
        m_Car_SelectSteeringWheel = m_Car.FindAction("SelectSteeringWheel", throwIfNotFound: true);
        m_Car_UndoKeyBoard = m_Car.FindAction("UndoKeyBoard", throwIfNotFound: true);
        m_Car_UndoSteeringWheel = m_Car.FindAction("UndoSteeringWheel", throwIfNotFound: true);
    }

    ~@KeyBoardInputActions()
    {
        UnityEngine.Debug.Assert(!m_Car.enabled, "This will cause a leak and performance issues, KeyBoardInputActions.Car.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Car
    private readonly InputActionMap m_Car;
    private List<ICarActions> m_CarActionsCallbackInterfaces = new List<ICarActions>();
    private readonly InputAction m_Car_FrontMoveKeyBoard;
    private readonly InputAction m_Car_FrontMoveSteeringWheel;
    private readonly InputAction m_Car_LeftRightMoveKeyBoard;
    private readonly InputAction m_Car_LeftRightMoveSteeringWheel;
    private readonly InputAction m_Car_BreakKeyBoard;
    private readonly InputAction m_Car_BreakSteeringWheel;
    private readonly InputAction m_Car_LeftRightKeyBoard;
    private readonly InputAction m_Car_LeftRightSteeringWheel;
    private readonly InputAction m_Car_UpDownKeyBoard;
    private readonly InputAction m_Car_UpDownSteeringWheel;
    private readonly InputAction m_Car_LightControlKeyBoard;
    private readonly InputAction m_Car_LightControlSteeringWheel;
    private readonly InputAction m_Car_GearChangeKeyBoard;
    private readonly InputAction m_Car_GearChangeSteeringWheel;
    private readonly InputAction m_Car_SideBreakKeyBoard;
    private readonly InputAction m_Car_SideBreakSteeringWheel;
    private readonly InputAction m_Car_SettingsKeyBoard;
    private readonly InputAction m_Car_SettingsSteeringWheel;
    private readonly InputAction m_Car_SelectKeyBoard;
    private readonly InputAction m_Car_SelectSteeringWheel;
    private readonly InputAction m_Car_UndoKeyBoard;
    private readonly InputAction m_Car_UndoSteeringWheel;
    /// <summary>
    /// Provides access to input actions defined in input action map "Car".
    /// </summary>
    public struct CarActions
    {
        private @KeyBoardInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public CarActions(@KeyBoardInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Car/FrontMoveKeyBoard".
        /// </summary>
        public InputAction @FrontMoveKeyBoard => m_Wrapper.m_Car_FrontMoveKeyBoard;
        /// <summary>
        /// Provides access to the underlying input action "Car/FrontMoveSteeringWheel".
        /// </summary>
        public InputAction @FrontMoveSteeringWheel => m_Wrapper.m_Car_FrontMoveSteeringWheel;
        /// <summary>
        /// Provides access to the underlying input action "Car/LeftRightMoveKeyBoard".
        /// </summary>
        public InputAction @LeftRightMoveKeyBoard => m_Wrapper.m_Car_LeftRightMoveKeyBoard;
        /// <summary>
        /// Provides access to the underlying input action "Car/LeftRightMoveSteeringWheel".
        /// </summary>
        public InputAction @LeftRightMoveSteeringWheel => m_Wrapper.m_Car_LeftRightMoveSteeringWheel;
        /// <summary>
        /// Provides access to the underlying input action "Car/BreakKeyBoard".
        /// </summary>
        public InputAction @BreakKeyBoard => m_Wrapper.m_Car_BreakKeyBoard;
        /// <summary>
        /// Provides access to the underlying input action "Car/BreakSteeringWheel".
        /// </summary>
        public InputAction @BreakSteeringWheel => m_Wrapper.m_Car_BreakSteeringWheel;
        /// <summary>
        /// Provides access to the underlying input action "Car/LeftRightKeyBoard".
        /// </summary>
        public InputAction @LeftRightKeyBoard => m_Wrapper.m_Car_LeftRightKeyBoard;
        /// <summary>
        /// Provides access to the underlying input action "Car/LeftRightSteeringWheel".
        /// </summary>
        public InputAction @LeftRightSteeringWheel => m_Wrapper.m_Car_LeftRightSteeringWheel;
        /// <summary>
        /// Provides access to the underlying input action "Car/UpDownKeyBoard".
        /// </summary>
        public InputAction @UpDownKeyBoard => m_Wrapper.m_Car_UpDownKeyBoard;
        /// <summary>
        /// Provides access to the underlying input action "Car/UpDownSteeringWheel".
        /// </summary>
        public InputAction @UpDownSteeringWheel => m_Wrapper.m_Car_UpDownSteeringWheel;
        /// <summary>
        /// Provides access to the underlying input action "Car/LightControlKeyBoard".
        /// </summary>
        public InputAction @LightControlKeyBoard => m_Wrapper.m_Car_LightControlKeyBoard;
        /// <summary>
        /// Provides access to the underlying input action "Car/LightControlSteeringWheel".
        /// </summary>
        public InputAction @LightControlSteeringWheel => m_Wrapper.m_Car_LightControlSteeringWheel;
        /// <summary>
        /// Provides access to the underlying input action "Car/GearChangeKeyBoard".
        /// </summary>
        public InputAction @GearChangeKeyBoard => m_Wrapper.m_Car_GearChangeKeyBoard;
        /// <summary>
        /// Provides access to the underlying input action "Car/GearChangeSteeringWheel".
        /// </summary>
        public InputAction @GearChangeSteeringWheel => m_Wrapper.m_Car_GearChangeSteeringWheel;
        /// <summary>
        /// Provides access to the underlying input action "Car/SideBreakKeyBoard".
        /// </summary>
        public InputAction @SideBreakKeyBoard => m_Wrapper.m_Car_SideBreakKeyBoard;
        /// <summary>
        /// Provides access to the underlying input action "Car/SideBreakSteeringWheel".
        /// </summary>
        public InputAction @SideBreakSteeringWheel => m_Wrapper.m_Car_SideBreakSteeringWheel;
        /// <summary>
        /// Provides access to the underlying input action "Car/SettingsKeyBoard".
        /// </summary>
        public InputAction @SettingsKeyBoard => m_Wrapper.m_Car_SettingsKeyBoard;
        /// <summary>
        /// Provides access to the underlying input action "Car/SettingsSteeringWheel".
        /// </summary>
        public InputAction @SettingsSteeringWheel => m_Wrapper.m_Car_SettingsSteeringWheel;
        /// <summary>
        /// Provides access to the underlying input action "Car/SelectKeyBoard".
        /// </summary>
        public InputAction @SelectKeyBoard => m_Wrapper.m_Car_SelectKeyBoard;
        /// <summary>
        /// Provides access to the underlying input action "Car/SelectSteeringWheel".
        /// </summary>
        public InputAction @SelectSteeringWheel => m_Wrapper.m_Car_SelectSteeringWheel;
        /// <summary>
        /// Provides access to the underlying input action "Car/UndoKeyBoard".
        /// </summary>
        public InputAction @UndoKeyBoard => m_Wrapper.m_Car_UndoKeyBoard;
        /// <summary>
        /// Provides access to the underlying input action "Car/UndoSteeringWheel".
        /// </summary>
        public InputAction @UndoSteeringWheel => m_Wrapper.m_Car_UndoSteeringWheel;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Car; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="CarActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(CarActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="CarActions" />
        public void AddCallbacks(ICarActions instance)
        {
            if (instance == null || m_Wrapper.m_CarActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CarActionsCallbackInterfaces.Add(instance);
            @FrontMoveKeyBoard.started += instance.OnFrontMoveKeyBoard;
            @FrontMoveKeyBoard.performed += instance.OnFrontMoveKeyBoard;
            @FrontMoveKeyBoard.canceled += instance.OnFrontMoveKeyBoard;
            @FrontMoveSteeringWheel.started += instance.OnFrontMoveSteeringWheel;
            @FrontMoveSteeringWheel.performed += instance.OnFrontMoveSteeringWheel;
            @FrontMoveSteeringWheel.canceled += instance.OnFrontMoveSteeringWheel;
            @LeftRightMoveKeyBoard.started += instance.OnLeftRightMoveKeyBoard;
            @LeftRightMoveKeyBoard.performed += instance.OnLeftRightMoveKeyBoard;
            @LeftRightMoveKeyBoard.canceled += instance.OnLeftRightMoveKeyBoard;
            @LeftRightMoveSteeringWheel.started += instance.OnLeftRightMoveSteeringWheel;
            @LeftRightMoveSteeringWheel.performed += instance.OnLeftRightMoveSteeringWheel;
            @LeftRightMoveSteeringWheel.canceled += instance.OnLeftRightMoveSteeringWheel;
            @BreakKeyBoard.started += instance.OnBreakKeyBoard;
            @BreakKeyBoard.performed += instance.OnBreakKeyBoard;
            @BreakKeyBoard.canceled += instance.OnBreakKeyBoard;
            @BreakSteeringWheel.started += instance.OnBreakSteeringWheel;
            @BreakSteeringWheel.performed += instance.OnBreakSteeringWheel;
            @BreakSteeringWheel.canceled += instance.OnBreakSteeringWheel;
            @LeftRightKeyBoard.started += instance.OnLeftRightKeyBoard;
            @LeftRightKeyBoard.performed += instance.OnLeftRightKeyBoard;
            @LeftRightKeyBoard.canceled += instance.OnLeftRightKeyBoard;
            @LeftRightSteeringWheel.started += instance.OnLeftRightSteeringWheel;
            @LeftRightSteeringWheel.performed += instance.OnLeftRightSteeringWheel;
            @LeftRightSteeringWheel.canceled += instance.OnLeftRightSteeringWheel;
            @UpDownKeyBoard.started += instance.OnUpDownKeyBoard;
            @UpDownKeyBoard.performed += instance.OnUpDownKeyBoard;
            @UpDownKeyBoard.canceled += instance.OnUpDownKeyBoard;
            @UpDownSteeringWheel.started += instance.OnUpDownSteeringWheel;
            @UpDownSteeringWheel.performed += instance.OnUpDownSteeringWheel;
            @UpDownSteeringWheel.canceled += instance.OnUpDownSteeringWheel;
            @LightControlKeyBoard.started += instance.OnLightControlKeyBoard;
            @LightControlKeyBoard.performed += instance.OnLightControlKeyBoard;
            @LightControlKeyBoard.canceled += instance.OnLightControlKeyBoard;
            @LightControlSteeringWheel.started += instance.OnLightControlSteeringWheel;
            @LightControlSteeringWheel.performed += instance.OnLightControlSteeringWheel;
            @LightControlSteeringWheel.canceled += instance.OnLightControlSteeringWheel;
            @GearChangeKeyBoard.started += instance.OnGearChangeKeyBoard;
            @GearChangeKeyBoard.performed += instance.OnGearChangeKeyBoard;
            @GearChangeKeyBoard.canceled += instance.OnGearChangeKeyBoard;
            @GearChangeSteeringWheel.started += instance.OnGearChangeSteeringWheel;
            @GearChangeSteeringWheel.performed += instance.OnGearChangeSteeringWheel;
            @GearChangeSteeringWheel.canceled += instance.OnGearChangeSteeringWheel;
            @SideBreakKeyBoard.started += instance.OnSideBreakKeyBoard;
            @SideBreakKeyBoard.performed += instance.OnSideBreakKeyBoard;
            @SideBreakKeyBoard.canceled += instance.OnSideBreakKeyBoard;
            @SideBreakSteeringWheel.started += instance.OnSideBreakSteeringWheel;
            @SideBreakSteeringWheel.performed += instance.OnSideBreakSteeringWheel;
            @SideBreakSteeringWheel.canceled += instance.OnSideBreakSteeringWheel;
            @SettingsKeyBoard.started += instance.OnSettingsKeyBoard;
            @SettingsKeyBoard.performed += instance.OnSettingsKeyBoard;
            @SettingsKeyBoard.canceled += instance.OnSettingsKeyBoard;
            @SettingsSteeringWheel.started += instance.OnSettingsSteeringWheel;
            @SettingsSteeringWheel.performed += instance.OnSettingsSteeringWheel;
            @SettingsSteeringWheel.canceled += instance.OnSettingsSteeringWheel;
            @SelectKeyBoard.started += instance.OnSelectKeyBoard;
            @SelectKeyBoard.performed += instance.OnSelectKeyBoard;
            @SelectKeyBoard.canceled += instance.OnSelectKeyBoard;
            @SelectSteeringWheel.started += instance.OnSelectSteeringWheel;
            @SelectSteeringWheel.performed += instance.OnSelectSteeringWheel;
            @SelectSteeringWheel.canceled += instance.OnSelectSteeringWheel;
            @UndoKeyBoard.started += instance.OnUndoKeyBoard;
            @UndoKeyBoard.performed += instance.OnUndoKeyBoard;
            @UndoKeyBoard.canceled += instance.OnUndoKeyBoard;
            @UndoSteeringWheel.started += instance.OnUndoSteeringWheel;
            @UndoSteeringWheel.performed += instance.OnUndoSteeringWheel;
            @UndoSteeringWheel.canceled += instance.OnUndoSteeringWheel;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="CarActions" />
        private void UnregisterCallbacks(ICarActions instance)
        {
            @FrontMoveKeyBoard.started -= instance.OnFrontMoveKeyBoard;
            @FrontMoveKeyBoard.performed -= instance.OnFrontMoveKeyBoard;
            @FrontMoveKeyBoard.canceled -= instance.OnFrontMoveKeyBoard;
            @FrontMoveSteeringWheel.started -= instance.OnFrontMoveSteeringWheel;
            @FrontMoveSteeringWheel.performed -= instance.OnFrontMoveSteeringWheel;
            @FrontMoveSteeringWheel.canceled -= instance.OnFrontMoveSteeringWheel;
            @LeftRightMoveKeyBoard.started -= instance.OnLeftRightMoveKeyBoard;
            @LeftRightMoveKeyBoard.performed -= instance.OnLeftRightMoveKeyBoard;
            @LeftRightMoveKeyBoard.canceled -= instance.OnLeftRightMoveKeyBoard;
            @LeftRightMoveSteeringWheel.started -= instance.OnLeftRightMoveSteeringWheel;
            @LeftRightMoveSteeringWheel.performed -= instance.OnLeftRightMoveSteeringWheel;
            @LeftRightMoveSteeringWheel.canceled -= instance.OnLeftRightMoveSteeringWheel;
            @BreakKeyBoard.started -= instance.OnBreakKeyBoard;
            @BreakKeyBoard.performed -= instance.OnBreakKeyBoard;
            @BreakKeyBoard.canceled -= instance.OnBreakKeyBoard;
            @BreakSteeringWheel.started -= instance.OnBreakSteeringWheel;
            @BreakSteeringWheel.performed -= instance.OnBreakSteeringWheel;
            @BreakSteeringWheel.canceled -= instance.OnBreakSteeringWheel;
            @LeftRightKeyBoard.started -= instance.OnLeftRightKeyBoard;
            @LeftRightKeyBoard.performed -= instance.OnLeftRightKeyBoard;
            @LeftRightKeyBoard.canceled -= instance.OnLeftRightKeyBoard;
            @LeftRightSteeringWheel.started -= instance.OnLeftRightSteeringWheel;
            @LeftRightSteeringWheel.performed -= instance.OnLeftRightSteeringWheel;
            @LeftRightSteeringWheel.canceled -= instance.OnLeftRightSteeringWheel;
            @UpDownKeyBoard.started -= instance.OnUpDownKeyBoard;
            @UpDownKeyBoard.performed -= instance.OnUpDownKeyBoard;
            @UpDownKeyBoard.canceled -= instance.OnUpDownKeyBoard;
            @UpDownSteeringWheel.started -= instance.OnUpDownSteeringWheel;
            @UpDownSteeringWheel.performed -= instance.OnUpDownSteeringWheel;
            @UpDownSteeringWheel.canceled -= instance.OnUpDownSteeringWheel;
            @LightControlKeyBoard.started -= instance.OnLightControlKeyBoard;
            @LightControlKeyBoard.performed -= instance.OnLightControlKeyBoard;
            @LightControlKeyBoard.canceled -= instance.OnLightControlKeyBoard;
            @LightControlSteeringWheel.started -= instance.OnLightControlSteeringWheel;
            @LightControlSteeringWheel.performed -= instance.OnLightControlSteeringWheel;
            @LightControlSteeringWheel.canceled -= instance.OnLightControlSteeringWheel;
            @GearChangeKeyBoard.started -= instance.OnGearChangeKeyBoard;
            @GearChangeKeyBoard.performed -= instance.OnGearChangeKeyBoard;
            @GearChangeKeyBoard.canceled -= instance.OnGearChangeKeyBoard;
            @GearChangeSteeringWheel.started -= instance.OnGearChangeSteeringWheel;
            @GearChangeSteeringWheel.performed -= instance.OnGearChangeSteeringWheel;
            @GearChangeSteeringWheel.canceled -= instance.OnGearChangeSteeringWheel;
            @SideBreakKeyBoard.started -= instance.OnSideBreakKeyBoard;
            @SideBreakKeyBoard.performed -= instance.OnSideBreakKeyBoard;
            @SideBreakKeyBoard.canceled -= instance.OnSideBreakKeyBoard;
            @SideBreakSteeringWheel.started -= instance.OnSideBreakSteeringWheel;
            @SideBreakSteeringWheel.performed -= instance.OnSideBreakSteeringWheel;
            @SideBreakSteeringWheel.canceled -= instance.OnSideBreakSteeringWheel;
            @SettingsKeyBoard.started -= instance.OnSettingsKeyBoard;
            @SettingsKeyBoard.performed -= instance.OnSettingsKeyBoard;
            @SettingsKeyBoard.canceled -= instance.OnSettingsKeyBoard;
            @SettingsSteeringWheel.started -= instance.OnSettingsSteeringWheel;
            @SettingsSteeringWheel.performed -= instance.OnSettingsSteeringWheel;
            @SettingsSteeringWheel.canceled -= instance.OnSettingsSteeringWheel;
            @SelectKeyBoard.started -= instance.OnSelectKeyBoard;
            @SelectKeyBoard.performed -= instance.OnSelectKeyBoard;
            @SelectKeyBoard.canceled -= instance.OnSelectKeyBoard;
            @SelectSteeringWheel.started -= instance.OnSelectSteeringWheel;
            @SelectSteeringWheel.performed -= instance.OnSelectSteeringWheel;
            @SelectSteeringWheel.canceled -= instance.OnSelectSteeringWheel;
            @UndoKeyBoard.started -= instance.OnUndoKeyBoard;
            @UndoKeyBoard.performed -= instance.OnUndoKeyBoard;
            @UndoKeyBoard.canceled -= instance.OnUndoKeyBoard;
            @UndoSteeringWheel.started -= instance.OnUndoSteeringWheel;
            @UndoSteeringWheel.performed -= instance.OnUndoSteeringWheel;
            @UndoSteeringWheel.canceled -= instance.OnUndoSteeringWheel;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CarActions.UnregisterCallbacks(ICarActions)" />.
        /// </summary>
        /// <seealso cref="CarActions.UnregisterCallbacks(ICarActions)" />
        public void RemoveCallbacks(ICarActions instance)
        {
            if (m_Wrapper.m_CarActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="CarActions.AddCallbacks(ICarActions)" />
        /// <seealso cref="CarActions.RemoveCallbacks(ICarActions)" />
        /// <seealso cref="CarActions.UnregisterCallbacks(ICarActions)" />
        public void SetCallbacks(ICarActions instance)
        {
            foreach (var item in m_Wrapper.m_CarActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CarActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="CarActions" /> instance referencing this action map.
    /// </summary>
    public CarActions @Car => new CarActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard & Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_SteeringWheelSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme SteeringWheelScheme
    {
        get
        {
            if (m_SteeringWheelSchemeIndex == -1) m_SteeringWheelSchemeIndex = asset.FindControlSchemeIndex("Steering Wheel");
            return asset.controlSchemes[m_SteeringWheelSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Car" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="CarActions.AddCallbacks(ICarActions)" />
    /// <seealso cref="CarActions.RemoveCallbacks(ICarActions)" />
    public interface ICarActions
    {
        /// <summary>
        /// Method invoked when associated input action "FrontMoveKeyBoard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFrontMoveKeyBoard(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FrontMoveSteeringWheel" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFrontMoveSteeringWheel(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftRightMoveKeyBoard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftRightMoveKeyBoard(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftRightMoveSteeringWheel" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftRightMoveSteeringWheel(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BreakKeyBoard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBreakKeyBoard(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BreakSteeringWheel" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBreakSteeringWheel(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftRightKeyBoard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftRightKeyBoard(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftRightSteeringWheel" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftRightSteeringWheel(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UpDownKeyBoard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUpDownKeyBoard(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UpDownSteeringWheel" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUpDownSteeringWheel(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LightControlKeyBoard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLightControlKeyBoard(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LightControlSteeringWheel" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLightControlSteeringWheel(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "GearChangeKeyBoard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGearChangeKeyBoard(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "GearChangeSteeringWheel" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGearChangeSteeringWheel(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SideBreakKeyBoard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSideBreakKeyBoard(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SideBreakSteeringWheel" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSideBreakSteeringWheel(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SettingsKeyBoard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSettingsKeyBoard(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SettingsSteeringWheel" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSettingsSteeringWheel(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectKeyBoard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectKeyBoard(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectSteeringWheel" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectSteeringWheel(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UndoKeyBoard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUndoKeyBoard(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UndoSteeringWheel" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUndoSteeringWheel(InputAction.CallbackContext context);
    }
}
